services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: terraform-20241225044214108500000001.cpqie04uw3za.ap-southeast-1.rds.amazonaws.com
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin#123
      MYSQL_DB: todo_app_db

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todo_app_db

volumes:
  todo-mysql-data:
