services:
  app:
    image: node:18-alpine
    command: sh -c "cd /app && yarn install && yarn run dev"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - todo-app-node-modules:/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  todo-app-node-modules: