services:
  app:
    image: node:18-alpine
    command: sh -c "cd /app && yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env