name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        run: |
          docker build -t app .
          docker push app
      - name: Deploy to EC2
        run: |
          ssh -i "cloud_project.pem" ec2-user@${{secrets.EC2_HOST}} "docker pull app && docker run -d app"
