name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: MYSQL_HOST,MYSQL_USER,MYSQL_PASSWORD,MYSQL_DATABASE
          script: |
            # Navigate to home directory
            cd /home/ec2-user
            
            # Stop and remove existing container
            sudo docker stop brave_lumiere || true
            sudo docker rm brave_lumiere || true
            
            # Remove old project directory completely
            sudo rm -rf cloud-computing-project
            
            # Clone the latest code
            git clone https://github.com/g3-cloud-computing-project/cloud-computing-project.git
            cd cloud-computing-project
            
            # Create .env file
            cat > .env << EOF
            DB_HOST=${MYSQL_HOST}
            DB_USER=${MYSQL_USER}
            DB_PASSWORD=${MYSQL_PASSWORD}
            DB_NAME=${MYSQL_DATABASE}
            EOF
            
            # Remove old image
            sudo docker rmi cloud-computing-project:latest || true
            
            # Build new image
            sudo docker build -t cloud-computing-project:latest .
            
            # Run new container
            sudo docker run -d \
              --name brave_lumiere \
              -p 80:3000 \
              -e MYSQL_HOST="${MYSQL_HOST}" \
              -e MYSQL_USER="${MYSQL_USER}" \
              -e MYSQL_PASSWORD="${MYSQL_PASSWORD}" \
              -e MYSQL_DB="${MYSQL_DATABASE}" \
              cloud-computing-project:latest
            
            # Verify new container
            echo "New container details:"
            sudo docker ps | grep brave_lumiere
            
            # Show the version of index.html in container
            echo "Content of index.html in container:"
            sudo docker exec brave_lumiere cat /app/src/static/index.html