name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: MYSQL_HOST,MYSQL_USER,MYSQL_PASSWORD,MYSQL_DATABASE
          script: |
            # Stop and remove existing container
            sudo docker stop brave_lumiere || true
            sudo docker rm brave_lumiere || true
            
            # Remove old image with force
            sudo docker rmi -f cloud-computing-project:latest || true
            
            # Clean up any old code
            cd /home/ec2-user
            rm -rf cloud-computing-project
            
            # Clone latest code
            git clone https://github.com/g3-cloud-computing-project/cloud-computing-project.git
            cd cloud-computing-project
            
            # Print the content of index.html to verify we have the latest version
            echo "Checking index.html content:"
            cat index.html
            
            # Build new image with no cache
            sudo docker build --no-cache -t cloud-computing-project:latest .
            
            # Run new container with no cache volumes
            sudo docker run -d \
              --name brave_lumiere \
              --no-cache \
              -p 80:3000 \
              -e MYSQL_HOST="${MYSQL_HOST}" \
              -e MYSQL_USER="${MYSQL_USER}" \
              -e MYSQL_PASSWORD="${MYSQL_PASSWORD}" \
              -e MYSQL_DATABASE="${MYSQL_DATABASE}" \
              cloud-computing-project:latest

            # Verify deployment
            echo "Container is running with ID:"
            sudo docker ps -q --filter name=brave_lumiere
            
            # Print container logs
            echo "Container logs:"
            sleep 5
            sudo docker logs brave_lumiere
            
            # Check files in container
            echo "Files in container:"
            sudo docker exec brave_lumiere ls -la /app