name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    # containter: 
    #   image: node:20
    # steps:
    #   - uses : actions/checkout@v3
    #     with:
    #       node-version: 20
    #   - run: npm ci
    #   - run: npm run build
    #   - run: npm

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t todo-app .

    # Step 4: Deploy to EC2
    - name: Deploy Docker container
      run: |
        ssh -o StrictHostKeyChecking=no -i ./ec2-key.pem ec2-user@<EC2_PUBLIC_IP> << EOF
        docker stop todo-app-container || true
        docker rm todo-app-container || true
        docker run -d -p 3000:3000 --env-file .env --name todo-app-container todo-app
        EOF
