name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: MYSQL_HOST,MYSQL_USER,MYSQL_PASSWORD,MYSQL_DATABASE
          script: |
            # Clean up existing container and image
            sudo docker stop todo-app || true
            sudo docker rm todo-app || true
            sudo docker rmi todo-app-image || true
            
            # Clone latest code
            cd /home/ec2-user
            rm -rf cloud-computing-project
            git clone https://github.com/g3-cloud-computing-project/cloud-computing-project.git
            cd cloud-computing-project
            
            # Build and run new container
            sudo docker build -t todo-app-image .
            sudo docker run -d \
              --name todo-app \
              -p 80:3000 \
              -e MYSQL_HOST="${MYSQL_HOST}" \
              -e MYSQL_USER="${MYSQL_USER}" \
              -e MYSQL_PASSWORD="${MYSQL_PASSWORD}" \
              -e MYSQL_DATABASE="${MYSQL_DATABASE}" \
              todo-app-image

            # Show container status
            sudo docker ps | grep todo-app