name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Add Docker permissions
            sudo usermod -aG docker $USER
            sudo systemctl restart docker
            
            # Setup application directory
            cd /home/ec2-user
            sudo rm -rf todo-app
            sudo mkdir -p todo-app
            sudo chown -R ec2-user:ec2-user todo-app
            cd todo-app
            
            # Clone repository
            git clone https://github.com/g3-cloud-computing-project/cloud-computing-project.git .
            
            # Copy the .env file (make sure it exists in the EC2 instance)
            cp /home/ec2-user/.env .
            
            # Stop and remove existing containers
            sudo docker-compose down || true
            
            # Build and start with docker-compose
            sudo docker-compose up -d --build
            
            # Debug commands
            echo "Checking container status..."
            sudo docker ps
            echo "Checking container logs..."
            sudo docker logs todo-app
            echo "Checking if application is responding..."
            curl -v localhost:3000